# ---------------------------------------------------------------------------
# Persist shared model-profile and credential configuration in ~/.aab/.env.
# ---------------------------------------------------------------------------
configure_aab_env_file() {
    mkdir -p "${AAB_DIR}"
    chmod 700 "${AAB_DIR}"

    local claude_first_party_profiles claude_third_party_profiles
    local codex_first_party_profiles codex_third_party_profiles pi_profiles
    claude_first_party_profiles=$(_profile_list_for claude first-party)
    claude_third_party_profiles=$(_profile_list_for claude third-party)
    codex_first_party_profiles=$(_profile_list_for codex first-party)
    codex_third_party_profiles=$(_profile_list_for codex third-party)
    pi_profiles=$(_profile_list_for pi third-party)

    local -A claude_profile=() codex_profile=() pi_profile=()
    resolve_model_profile claude claude_profile
    resolve_model_profile codex codex_profile
    local pi_profile_name=""
    if resolve_model_profile pi pi_profile; then
        pi_profile_name="${pi_profile[name]}"
    fi

    local tmp
    tmp=$(mktemp "${AAB_ENV_FILE}.tmp.XXXXXX")
    {
        printf '# Written by autonomous-agent-bootstrap. Re-run bootstrap.bash to update.\n'
        _write_shell_export AAB_CLAUDE_FIRST_PARTY_PROFILES "$claude_first_party_profiles"
        _write_shell_export AAB_CLAUDE_THIRD_PARTY_PROFILES "$claude_third_party_profiles"
        _write_shell_export AAB_CLAUDE_DEFAULT_PROFILE "${claude_profile[source]}/${claude_profile[name]}"
        _write_shell_export AAB_CODEX_FIRST_PARTY_PROFILES "$codex_first_party_profiles"
        _write_shell_export AAB_CODEX_THIRD_PARTY_PROFILES "$codex_third_party_profiles"
        _write_shell_export AAB_CODEX_DEFAULT_PROFILE "${codex_profile[source]}/${codex_profile[name]}"
        _write_shell_export AAB_PI_PROFILES "$pi_profiles"
        _write_shell_export AAB_PI_DEFAULT_PROFILE "$pi_profile_name"
        _write_shell_export AAB_INFERENCE_GATEWAY_URL "${AAB_INFERENCE_GATEWAY_URL:-}"
        _write_shell_export AAB_INFERENCE_GATEWAY_API_KEY "${AAB_INFERENCE_GATEWAY_API_KEY:-}"
        _write_shell_export AAB_ANTHROPIC_API_KEY "${AAB_ANTHROPIC_API_KEY:-}"
        _write_shell_export AAB_OPENAI_API_KEY "${AAB_OPENAI_API_KEY:-}"
        _write_shell_export AAB_CODEX_SERVICE_TIER "${AAB_CODEX_SERVICE_TIER:-$DEFAULT_CODEX_SERVICE_TIER}"
        _write_shell_export AAB_CODEX_AGENT_MAX_THREADS "${AAB_CODEX_AGENT_MAX_THREADS:-$DEFAULT_CODEX_AGENT_MAX_THREADS}"
        _write_shell_export AAB_GH_TOKEN "${AAB_GH_TOKEN:-}"
        _write_shell_export AAB_BREV_API_KEY "${AAB_BREV_API_KEY:-}"
        _write_shell_export AAB_BREV_ORG_ID "${AAB_BREV_ORG_ID:-}"
    } > "$tmp"
    chmod 600 "$tmp"
    mv -f "$tmp" "$AAB_ENV_FILE"
    log "Wrote ${AAB_ENV_FILE} (claude_profile=${claude_profile[source]}/${claude_profile[name]}, codex_profile=${codex_profile[source]}/${codex_profile[name]}, pi_profile=${pi_profile_name:-none})."
}

configure_github_shell() {
    mkdir -p "${AAB_SHELL_CONFIG_DIR}"
    local tmp
    tmp=$(mktemp "${GITHUB_SHELL_CONFIG_FILE}.tmp.XXXXXX")
    {
        printf '# Generated by autonomous-agent-bootstrap.\n'
        if [ -n "${AAB_GH_TOKEN:-}" ]; then
            _write_shell_export GH_TOKEN "$AAB_GH_TOKEN"
        fi
    } > "$tmp"
    chmod 0600 "$tmp"
    mv -f "$tmp" "${GITHUB_SHELL_CONFIG_FILE}"
    log "Wrote GitHub shell configuration to ${GITHUB_SHELL_CONFIG_FILE}."
}
